version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "langchain_app"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    container_name: my-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "langchain_app"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      GOOGLE_API_KEY: "AIzaSyCMm3lgZTAgIF3oaG_jjvEiSFtFJCHEtHo"

volumes:
  db_data:
